# MOST OF TIMES WE CANNOT HARDCODE THE VALUES AND WE CANNOT DO FOR COMMAND SUBSTITUTION
# SO WE NEED TO ASK FOR USER TO GIVE INPUT
# WHILE EXECUTING THE SCRIPT WE WILL USE "read" TO HAVE INPUT FROM HERE.
read -p 'ENTER YOUR NAME: ' name
read -p 'ENTER YOUR AGE: ' age
echo -e "your name = $name\nyour age = $age"
